[workspace]

members = [
	"cargo-pipe",
	"pipebase",
	"pipederive",
	"pipegen",
	"pipeware/pipecql",
	"pipeware/pipecsv",
	"pipeware/pipejson",
	"pipeware/pipekafka",
	"pipeware/pipekube",
	"pipeware/pipemysql",
	"pipeware/pipepsql",
	"pipeware/piperedis",
	"pipeware/pipereqwest",
	"pipeware/piperocksdb",
	"pipeware/pipes3",
	"pipeware/pipesqs",
	"pipeware/pipewarp",
]