version: '3.9'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - '2181:2181'
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    ports:
      - '9092:9092'
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DEV:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DEV
      KAFKA_ADVERTISED_LISTENERS: DEV://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1