version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=foo
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=foo
      - MYSQL_DATABASE=foo
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      interval: 3s
      retries: 3
  app:
    container_name: app
    build:
      context: ../
      args:
        TEST: ingest_mysql
        INIT_DELAY: 3
    depends_on: 
      - mysql
    ports:
      - "8000:8000"
      - "9000:9000"
    environment: 
      - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64