version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
  app:
    container_name: app
    build:
      context: ../
      args:
        EXAMPLE: ingest_redis_parallel
        INIT_DELAY: 3
    depends_on: 
      - redis
    ports:
      - "8000:8000"
      - "9000:9000"