[package]
name = "pipebase"
version = "0.1.0"
authors = ["Li Yu <li.yu.sh0211@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
log = "0.4.14"
tokio = { version = "0.2", features = ["full"] }
csv = "1.0.0"
serde_yaml = "0.8"
strum = { version = "0.20", features = ["derive"] }