version: '3.9'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - '2181:2181'
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    ports:
      - '9092:9092'
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DEV:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DEV
      KAFKA_ADVERTISED_LISTENERS: DEV://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafkacli:
    container_name: kafkacli
    image: confluentinc/cp-kafka
    depends_on: 
      - kafka
    command: ["sh", "-c", "sleep 5 && kafka-topics --create --topic records --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1"]
  app:
    container_name: app
    build:
      context: ../
      args:
        EXAMPLE: consume_kafka
        INIT_DELAY: 3
    depends_on: 
      - kafka
      - kafkacli
    ports:
      - "8000:8000"
      - "9000:9000"
