version: '3.9'

services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    ports:
      - '9200:9200'
      - '9300:9300'
    environment: 
      discovery.type: single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.4
    depends_on: 
      - elastic
    ports:
      - '5601:5601'
    environment: 
      ELASTICSEARCH_HOSTS: http://elastic:9200
