version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=foo
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=foo
      - MYSQL_DATABASE=foo