version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    container_name: app
    build:
      context: ../
      args:
        TEST: ingest_postgres
    depends_on: 
      - postgres
    ports:
      - "8000:8000"
      - "9000:9000"