on: 
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * *"

name: E2E

jobs:
  timer:
    name: Timer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/timer/docker-compose.yml up -d
      - uses: actions-rs/cargo@v1
        with: 
          command: test
          args: --package e2e_timer --features itest
  ingest_redis:
    name: Ingest Redis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/ingest_redis/docker-compose.yml up -d
      - uses: actions-rs/cargo@v1
        with: 
          command: test
          args: --package e2e_ingest_redis --features itest
  ingest_postgres:
    name: Ingest Postgres
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/ingest_postgres/docker-compose.yml up -d
      - name: wait for app setup
        run: sleep ${INITAL_DELAY}
        env: 
          INITAL_DELAY: 5
      - name: test
        run: ./e2e/run.sh -f e2e/ingest_postgres/entry.json
  pubsub_kafka:
    name: Pubsub Kafka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/pubsub_kafka/docker-compose.yml up -d
      - name: wait for app setup
        run: sleep ${INITAL_DELAY}
        env: 
          INITAL_DELAY: 30
      - name: test
        run: ./e2e/run.sh -f e2e/pubsub_kafka/entry.json
  ingest_mysql:
    name: Ingest Mysql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/ingest_mysql/docker-compose.yml up -d
      - name: wait for app setup
        run: sleep ${INITAL_DELAY}
        env: 
          INITAL_DELAY: 15
      - name: test
        run: ./e2e/run.sh -f e2e/ingest_mysql/entry.json
  ingest_cassandra:
    name: Ingest Cassandra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/ingest_cassandra/docker-compose.yml up -d
      - uses: actions-rs/cargo@v1
        with: 
          command: test
          args: --package e2e_ingest_cassandra --features itest
  ingest_elasticsearch:
    name: Ingest Elasticsearch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/ingest_elasticsearch/docker-compose.yml up -d
      - name: wait for app setup
        run: sleep ${INITAL_DELAY}
        env: 
          INITAL_DELAY: 30
      - name: test
        run: ./e2e/run.sh -f e2e/ingest_elasticsearch/entry.json
  pubsub_mqtt:
    name: Pubsub Mqtt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/pubsub_mqtt/docker-compose.yml up -d
      - name: wait for app setup
        run: sleep ${INITAL_DELAY}
        env: 
          INITAL_DELAY: 5
      - name: test
        run: ./e2e/run.sh -f e2e/pubsub_mqtt/entry.json
  pubsub_rabbitmq:
    name: Pubsub Rabbitmq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy project
        run: ./e2e/setup.sh -d .
      - name: run
        run: docker-compose -f e2e/pubsub_rabbitmq/docker-compose.yml up -d
      - name: wait for app setup
        run: sleep ${INITAL_DELAY}
        env: 
          INITAL_DELAY: 40
      - name: test
        run: ./e2e/run.sh -f e2e/pubsub_rabbitmq/entry.json
